---
# This workflow integrates ShiftLeft NG SAST with GitHub
# Visit https://docs.shiftleft.io for help
name: ShiftLeft-TD

on:
  workflow_dispatch:

jobs:        
  Review-Analysis: 
    runs-on: ubuntu-latest
    environment: Organizational Default
    needs: Perform-Analysis

    steps:
      - name: Check-Out Trigger Commit
        uses: actions/checkout@v3

      - name: Download ShiftLeft CLI
        run: |
          curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && \
          chmod a+rx ${GITHUB_WORKSPACE}/sl
      - name: Validate Build Rules
        run: |
          ${GITHUB_WORKSPACE}/sl check-analysis \
            --app sl-java-220822 \
            --v2 \
            --config ./shiftleft-failure.yml ; (( err |= $? ))
          ${GITHUB_WORKSPACE}/sl check-analysis \
            --app sl-java-220822 \
            --v2 \
            --config ./shiftleft-success.yml ; (( err |= $? ))            
        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
